########################################################
# Parameters for points aggregation in mapping context #
########################################################

leaf_size: 0.1 # Voxel size (eq approx space between points after downsampling)
max_size: 500. # Maximum size of the scene (from the last lidar slam position)
               # Warning : should be at least as large as one frame
min_points_per_voxel: 2 # Minimum number of points in a voxel to extract it as non moving object
min_dist_around_trajectory: 1. # Minimum distance of the points from the sensor to aggregate them

# Slice extraction parameters
slice:
  enable: false        # Enable or disable the slice extraction and the area computation
  traj_length: 1.      # [meters] Length of trajectory to consider to define the slice plane
  width: 0.2           # [meters] Width of the pointcloud slice to take to create the slice projection
  max_dist: 4.         # [meters] Maximal distance of the points from the trajectory position onto the slice plane
  angle_resolution: 3. # [Â°] Resolution of the slice pointcloud w.r.t the trajectory position